# COGS 108 - Data Checkpoint

## Authors

> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Group 89:

- Bowen Bothello: Writing - Background research, Conceptualization, Methodology
- Lawrence Hu: Writing - Data Curation, Revision and Editing, Conceptualization, Research Planning
- Janeen Taitingfong: Project Administration, Writing - Revision and Editing, Conceptualization, Background Research, Data Curation

## Research Question

What is the relationship between the sentiment of Steam games that include at least one of the top 10 most popular tags as defined by Steam (Indie, Action, Adventure, Casual, Single player, Simulation, RPG, Strategy, 2D, 3D) and community reception/rating on Steam between 2024 and early 2026? Has the reception changed significantly over this time frame, if so, are there certain tags that correlate with more positive, or negative reception on games? Are there certain tags that correlate with more positive, or negative reception on games?

## Background and Prior Work

The topic we will be focusing on is the general public response to video games developed towards various subjects. More specifically, how a video game’s categorization correlates to the audience’s response to said game as shown through user generated reviews on the Steam platform. We focus on the Steam platform as it is the most widely used PC gaming marketplace, and has games of all genres, styles, and development sizes which would be perfect for the accumulation of data we are researching <a name="valve1"></a>[<sup>5</sup>](#valve1). While games in media are typically taxidermied through single genre classifications, games on Steam are represented by a series of descriptive tags ranging from themes such as “atmospheric” or “horror”, to gameplay like “action” or “adventure”, and even production and style types such as “indie” or “casual”. This process of figuratively stacking classifications provides us the novel opportunity to consider more specific components present in games, and compare data across games with overlapping similarities from various genre groups <a name="tags"></a>[<sup>4</sup>](#tags). A standard user-generated Steam game review is composed of a rating of either positive or negative, and an optional textual review of the game written by the user <a name="valve2"></a>[<sup>6</sup>](#valve2).  In the following paragraphs, I will discuss the concepts of tags and genre in further detail as well as examine familiar research in this field of data study.

An important paper focused on understanding the significance of tags on the Steam platform is A Preliminary Network Analysis on Steam Game Tags: Another Way of Understanding Game Genres by Xiaozhou Li and Boyang Zhang, which discusses the current system of game classification, and the opportunities presented by the uniquely designed Steam tag system. In their research, they consider the user-generated tags on Steam as nodes of a network, with the capability for edges to form between two tags as long as both tags are annotated by the same gamer. Through their study they were able to determine the five most notable game tags, being “indie”, “action”, “adventure”, “singleplayer”, and “casual”, which shows that the tags attached to games span a range of production type, gameplay type, and number of players. This emphasizes the defining point that the standard perception a game from its genre doesn’t properly represent the true interconnectedness games have from one another in the same way that Steam tags do. To further emphasize this idea, the researchers also were able to group tags which fell under the concepts of certain genres, but concluded that it was impossible to find any game on Steam that can be solely classified under a single genre without having some type of element present under another genre<a name="tags"></a>[<sup>4</sup>](#tags). This research helps us understand the unique type of data that game tags presents to us, while also proving the difference our research would have over the genre-specific research to be defined in the following section.

Facebook IQ, in collaboration with external research organizations, conducted a global study of 13,412 mobile gamers across 11 countries segmented across 27 different mobile gaming genres and subgenres to explore their gaming behaviors while also utilizing facebook’s internal app events data to uncover behavioral insights across mobile gaming genres. Through their research, they discovered that the specific genre preferences vary significantly across countries, but some notable genres include matching puzzle games, card/casino games, racing games, and action RPG/MMORPG games which gives us a good insight into genre preferences in a gaming marketplace outside of Steam. Furthermore, the study also indicates that very few gamers play only one genre, with players in the US, UK, and South Korea reportedly playing an average of two distinct genres in a given month, while Japanese play three. This is important to note for our own study as it shows that the population of user responses to games on Steam aren’t evenly distributed between tags, with the expectation that single users may have reviewed multiple games of different categories within our data. Finally, we can learn that the study we will be conducting would be important, as across nine surveyed markets, nearly half of player responses say genre is important in their decision, greatly exceeding other considerations <a name="facebook"></a>[<sup>1</sup>](#facebook). 

The closest research we could find to our own focus of analyzing user response to games of different tags comes from the paper Prediction of the Most Popular Game Tags on Steam under the Influence of Covid-19 Based on Machine Learning and Natural Language Processing, in which the authors applied various machine learning algorithms to Steam’s game tags to create a prediction model. Unfortunately, due to the research’s minimal scope of data only relating to the Covid-19 pandemic, they were unable to find conclusive evidence of tag correlation using their various methods <a name="prediction"></a>[<sup>3</sup>](#prediction). From this, we can learn that for our own research we would need to accumulate a significant amount of data to achieve any type of valid conclusion. That being said, the paper From Fadas to Classics which analyzes the evolution of Steam Tags throughout the years, concludes that tag popularity tends to fluctuate with time, with many trends lasting about four years <a name="fads"></a>[<sup>2</sup>](#fads) which is important for us to keep in mind when accumulating our own data.

1. <a name="facebook"></a> [^](#facebook) Dring, C. (2020, September 22). Facebook: Why genre matters in mobile gaming. GamesIndustry.biz. https://www.gamesindustry.biz/facebook-why-genre-matters-in-mobile-gaming

2. <a name="fads"></a> [^](#fads) Grelier, N., Pfau, J., Mathieu, N., & Kaufmann, S. (2025). From Fads to Classics – Analyzing Video Game Trend Evolutions through Steam Tags. In arXiv. https://arxiv.org/

3. <a name="prediction"></a> [^](#prediction) Jihao Zhang, Hongzhi Zhao, Zhicheng Chen, Zihan Song. Prediction of the Most Popular Game Tags on Steam under the Influence of Covid-19 Based on Machine Learning and Natural Language Processing. The Frontiers of Society, Science and Technology (2020) Vol. 2 Issue 12: 70-80. https://doi.org/10.25236/FSST.2020.021212.

4. <a name="tags"></a> [^](#tags) Li, Xiaozhou & Zhang, Boyang. (2020). A preliminary network analysis on steam game tags: another way of understanding game genres. 65-73. 10.1145/3377290.3377300.

5. <a name="valve1"></a> [^](#valve1) Valve Corporation. (2019). Steam, The Ultimate Online Game Platform. Steampowered.com. https://store.steampowered.com/about/

6. <a name="valve2"></a> [^](#valve2) Valve Corporation. (2025). Steam Support :: User Reviews. Steampowered.com. https://help.steampowered.com/en/faqs/view/2DA6-9CB3-F84A-643E

## Hypothesis

We predict that a relationship between Steam game tags and the Steam community's reception and ratings does exist between 2024 and early 2026. We predict that the tags most representative of a game's genre (e.g Action, RPG) will have a more strongly positive correlation with positive reception, and we also predict that the tags most closely associated with competitive style games (i.e FPS, shooter, etc.) will have a more strongly positive correlation with negative reception. This can be evidenced from the background research found from Facebook IQ's genre analysis, which indicated some genres being more well recieved than others. Furthermore, the research done on the preliminary network analysis of steam game tags indicates some tags being more widely utilized than others, which furthers the notion of a true relationship between game tags and reception.

## Data

### Data overview
For each dataset include the following information
- Dataset #1
  - Dataset Name: Top 1000 Steam Games 2024-2026
  - Link to the dataset: https://www.kaggle.com/datasets/waddahali/top-1000-steam-games-20242026
  - Number of observations: 1000 (before dropping any NaN values)
  - Number of variables: 12
  - Description of the variables most relevant to this project
> AppID: Special ID number associated with Name <br>
> Name: Name of game <br>
> All_Tags: Top 10 tags associated with Name <br>
> Review_Score_Pct: Percent of positive reviews <br>
> Total_Reviews: Total number of reviews (necessary to calculate proportions)
  - Descriptions of any shortcomings this dataset has with repsect to the project
> The dataset, as it currently stands, has just under 1000 observations and we realize that the landscape of games is incredibly vast and our set is just a drop in the bucket. We are going to attempt to try and gather more observations during the last half of week 6 but for now, we are going to try and make do with this data set as it stands. Additionally, that also means we don't currently have columns for reviews and their corresponding timestamps, however, once we have curated and finalized our list of games, we will use the AppIDs to curate a list of reviews, their timestamps and whether they were positive or negative. We will keep these dataframes separate because many games will have a large amount of reviews, and we will use it as sort of a mediatary dataset to conduct the analysis.

In [ ]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [ ]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/COGS108/Group-SP26-089/refs/heads/main/data/00-raw/steam_games_2026.csv', 'filename':'steam_games_2026.csv'},
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

### Top 1000 Steam Games (currently as of March 2026)


Important metrics within our dataset, as it stands, are:
Game tags have no units, and they are purely for categorical purposes. Users can apply tags that describe the game (e.g visually, type of gameplay, etc) and they are supposed to be a good representation of the game itself. Games can have anywhere from 1 tag to dozens of tags, but for our purposes we kept it to the first 10 tags that the Steam page would show. Steam states that the order of tags is a demonstration of the popularity of that tag being applied to the game (i.e the more times a user applies that tag to the game, the higher up on the list it is). The review score percent is the percentage of all reviews that are positive. This metric is, ideally, an overall "score" of the game, out of 100, based on the proportion of user submitted reviews that are positive.

Some concerns we noticed with our data set is that some games have enormously large numbers of reviews compared to other games, and some factors that may have caused this could be how long the game has been released or how dedicated of a fanbase the game has curated. Additionally, reviews are either documented as positive or negative, and some reviews might include opinions that might be more represented by a "middle ground", however due to the sheer size and number of reviews and range of languages that reviews span, limiting the reviews to positive or negative might lead to a bias toward one reception that we do not have the time and processing power to specifically evaluate. Also, as of right now, our data set doesn't include the specific reviews and timestamps of the reviews for us to identify trends over time because we are currently attempting to curate more data to add onto this existing data set, but we were not able to access the processing power in time for this checkpoint as we are going to attempt to run the API on May 14th.

We will be honest and transparent, we have tested and confirmed that we can get access to every game's reviews and the timestamps on each review (so we can try to analyze any changes over time). We decided to demonstrate how we are able to access the game's reviews in the cell below our loading/cleaning/tidying/wrangling of our 1st data set to demonstrate to you that we are able to get necessary information not present in Dataset #1 that we will need for analysis for the next checkpoint.

In [6]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
import pandas as pd

# load csv file
data = pd.read_csv("./data/00-raw/steam_games_2026.csv")

# we only need AppID, Name, All_Tags, Review_Score_Pct
data = data[['AppID', 'Name', 'All_Tags', 'Review_Score_Pct', 'Total_Reviews']]

# remove any rows that have any null values
# we need a value for every column for identification or anaylsis purposes
data = data.dropna()

# because we're comparing tags to reviews, we also need to ensure that we only look at games that have reviews
# therefore we also need to drop rows that have 0 reviews
data = data[data['Total_Reviews'] > 0] # only keep entries with at least 1 review, might change later to be above a minimum threshold
data

,AppID,Name,All_Tags,Review_Score_Pct,Total_Reviews
0,730,Counter-Strike 2,FPS;Shooter;Multiplayer;Competitive;Action;Tea...,83,4980365
1,2868840,Slay the Spire 2,Strategy;Roguelike;Card Game;Deckbuilding;Co-o...,97,49549
3,3065800,Marathon,Extraction Shooter;PvP;Multiplayer;Sci-fi;Shoo...,90,24360
4,3764200,Resident Evil Requiem,Survival Horror;Zombies;Horror;Third-Person Sh...,96,79667
5,2157830,John Carpenter's Toxic Commando,Zombies;Shooter;Online Co-Op;FPS;PvE;Action;Ad...,83,2765
...,...,...,...,...,...
995,1202200,Paleo Pines,Dinosaurs;Farming Sim;Exploration;Relaxing;Ind...,93,1921
996,2753970,MARVEL Cosmic Invasion,Beat 'em up;Arcade;Pixel Graphics;Superhero;Co...,90,1630
997,1239080,Door Kickers 2: Task Force North,Tactical;Top-Down;Real Time Tactics;Real-Time ...,96,11539
998,1302240,Labyrinthine,Horror;Online Co-Op;Co-op;Puzzle;Psychological...,70,13549
999,917950,Vellum,Online Co-Op;Action Roguelike;Third-Person Sho...,90,1188

### Demonstration of Getting Game Reviews

We are using this cell to demonstrate how we will eventually access game reviews and their timestamps, as it will be necessary for our analysis later. We did not think it was feasible to try and put all of the reviews into one large data frame or have multiple large data frames as our list of games is already large. We will cross reference each through the AppID as it is each game's ID is unique

In [7]:
## import the API
%pip install steamreviews

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: steamreviews in /home/jtaitingfong/.local/lib/python3.11/site-packages (0.9.5)
Requirement already satisfied: requests in /home/jtaitingfong/.local/lib/python3.11/site-packages (from steamreviews) (2.33.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests->steamreviews) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests->steamreviews) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/conda/lib/python3.11/site-packages (from requests->steamreviews) (2.2.1)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.11/site-packages (from requests->steamreviews) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [13]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
import steamreviews
from datetime import datetime

# filter system
request_params = dict()
# Reference: https://partner.steamgames.com/doc/store/localization#supported_languages
request_params['language'] = 'english'
# Reference: https://partner.steamgames.com/doc/store/getreviews
request_params['review_type'] = 'positive'
request_params['purchase_type'] = 'steam'

# tester, using last AppID shown in data as shown above
app_id = 917950 # Vellum
review_dict, query_count = steamreviews.download_reviews_for_app_id(app_id, chosen_request_params=request_params)

# query_count = number of reviews
df = pd.DataFrame.from_dict(review_dict['reviews'])
df = df.transpose()
df.columns

# timestamp_created: timestamp of when review was posted (in unix)
# voted up: true if the review was positive, false otherwise

# add a new column to display the unix timestamp as a readable date
df['date'] = pd.to_datetime(df['timestamp_created'], unit='s').dt.year
df = df[['date', 'voted_up']]
df # display

# we would use the following command instead of the one above if we wanted the whole date
# df['date'] = pd.to_datetime(df['timestamp_created'], unit='s').dt.date

[appID = 917950] expected #reviews = 1024

           date voted_up
225318180  2026     True
225290356  2026     True
225247584  2026     True
224472572  2026     True
224167568  2026     True
...         ...      ...
161704098  2024     True
161700592  2024     True
161698141  2024     True
161693673  2024     True
161684441  2024     True

[1024 rows x 2 columns]

## Ethics

## Ethics 

feedback: Make sure to write something about downstream bias mitigation and unintended use cases.

### A. Data Collection
 - [ ] **A.1 Informed consent**: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data uses to which they consent?
> We do not have any direct human subjects, and all of the game analytics we plan on collecting will be through Valve's Steam Web API, which is collected and maintained by Valve, so all users consent to the data shown through Valve 

 - [X] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those?

> We considered that there are games that were released closer to the end of our time frame (specifically closer toward 2025) which may still have "relevancy bias" and may unintentionally have more positive reception and ratings than games that were released years before it. This is why we decided to look over the time frame of 2020-2025 with games that have a minimum number of relevant discussion posts, a number we have not completely finalized at this point in time.

 - [X] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?

> We will looking at ratings and reception, potentially through discussion posts, and we will not include profiles and, or, names of the poster. We will delete that column entirely, and instead replace it with the corresponding game ID/name to connect the post to the game. Poster profiles are not relevant for our analysis therefore we will do our best to not include it in any way.

 - [X] **A.4 Downstream bias mitigation**: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?

>  We have considered that testing the distribution of tags in the originally used dataset could potentially reveal biases. We acknowledge that we are limited and constrained to how Steam defines their Top rated games, and we can't control how much of any one tag is present in the data. We have decided that our tests would relate to checking tag distributions and trying to mitigate any downstream biases by possibly trying to collect more samples of tags with less presence to try and even out and any uneven distrbutions.

### B. Data Storage
 - [ ] **B.1 Data security**: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?
> No, because our data does not contain any personal or sensitive information, and all data comes directly from Steam Web API, a public database that anyone can access. 

 - [ ] **B.2 Right to be forgotten**: Do we have a mechanism through which an individual can request their personal information be removed?
> No, since our data collection mechanism and data points are all public entities and information on the Steam website, and we are not collecting any individual profiles or information about individuals.

 - [ ] **B.3 Data retention plan**: Is there a schedule or plan to delete the data after it is no longer needed?
> No, because as previously described, we are not collecting any personal information or any information outside of the data provided by Steam Web API (which we have no direct control over). And we want any future researchers who may find the data we collect from Steam useful to have it already collected for them. 

### C. Analysis
 - [ ] **C.1 Missing perspectives**: Have we sought to address blindspots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)?
> We aren't, as we are focused on quantitative data collection and analysis using data from a single platform which wouldn't have affected communities and lacks many subject matter experts outside of those who did the research referenced in the background and prior work section.

 - [X] **C.2 Dataset bias**: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)?

> We have examined the data for possible sources of bias (i.e relevancy bias) and the steps we have taken to mitigate these biases are as follow: ensuring that the game has at least one relevant game tag and that the game has a minimum number of related posts/reviews (a number we have not finalized at this point in time) to ensure a thorough analysis.

 - [ ] **C.3 Honest representation**: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?
> We will ensure that all the data analysis and visualization we will provide will not obscure any data or underlying results outside of our data filtering which would be properly documented in our analysis.
 - [X] **C.4 Privacy in analysis**: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?

> We have included in our initial plan to ensure that data with PII is not used in our analysis because we do not feel it has any sort of relevancy toward our analysis. If we are to grab that data during our scraping, we plan to delete it entirely from our dataset, or replace it with a different identifier that has no correlation to the PII that will help us keep our data organized and connected.

 - [X] **C.5 Auditability**: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?

> We are, at this point in time, currently documenting each steps of generating our analysis. We are separating each step clearly and simply to ensure that if something goes wrong, we know how to find the best "checkpoint" to return back to in order to fix any issues.


### D. Modeling
 - [X] **D.1 Proxy discrimination**: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory?
> The variables we will be utilizing are all sourced through Steam Web API, and we do not plan on omitting any of the reviews for any game unless they lack the necessary review post date or positive rating boolean, which we don't expect to occur.
 - [ ] **D.2 Fairness across groups**: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)?
> No, because we are not creating a model for prediction using our data.
 - [ ] **D.3 Metric selection**: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?
> No, because we are not creating a model for prediction using our data.
 - [ ] **D.4 Explainability**: Can we explain in understandable terms a decision the model made in cases where a justification is needed?
> No, because we are not creating a model for prediction using our data.
 - [ ] **D.5 Communicate limitations**: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?
> No, because we are not creating a model for prediction using our data.
### E. Deployment
 - [X] **E.1 Monitoring and evaluation**: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?
> No, because we are not creating a model for prediction using our data.
 - [ ] **E.2 Redress**: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?
> Since we are utilizing publicly accessible data through the Steam Web API and are focusing our research on a topic which won't directly affect human lives, we do not plan on discussing a response to user hard from our study.
 - [X] **E.3 Roll back**: Is there a way to turn off or roll back the model in production if necessary?
> No, because we are not creating a model for prediction using our data.
 - [X] **E.4 Unintended use**: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?

> We have identified that a possible unintended use could be that if we are to find that certain game tags correlate to a stronger positive reception by the community, game developers could add these tags to their games to push their game toward the top in the storefront. Regretfully, we acknowledge that we can't prevent and control how game developers tag their games, and we can't monitor every game that comes out and the tags that they have. While we will be weary of any references to our model and the way it's being used after its deployment, we will conduct our analysis thoughtfully and carefully to prevent as much misuse as possible.

## Team Expectations

* *We will meet at minimum once a week in person to discuss current progress and future expectations as of the meeting time*
* *We will communicate efficiently and promptly, always immediately updating our team if any issues or personal concerns arise*
* *We will be respectful of each other and differences in opinions or choices of methods and work to resolve them to the best of our ability*
* *We will all contribute toward our project and be communicative if we are unsure of any coding related issues*
* *We will be respectful but mindful of our remaining time and deadlines, and plan accordingly to ensure a successful final project*

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 5/1  |  8 PM (Zoom) | NA | Discuss & start building the web scraper | 
|  5/4 |  12 PM |  Begin work on web scraper | Continue work on scraper, discuss planned cleaning/tidying of data | 
|   | 10 AM  | Edit, finalize, and submit proposal; Search for datasets  | Discuss Wrangling and possible analytical approaches; Assign group members to lead each specific part   |
| 5/11  | 12 PM | Progress on gathering the data | Continue work on data wrangling and cleaning  |
| 5/13  | Before 11:59 PM | Sections assigned to complete on Checkpoint notebook | Submit Project Checkpoint #1 Data & look at currently curated data  |
| 5/14  | 8 PM (Zoom)  | NA | Quick chek-in on data curation |
| 5/18 | 12 PM | starting data set | finalize cleaning/tidying data, plan EDA and analysis  |
| 5/22 | 8 PM (Zoom) | Plan for analysis | Discuss plans, start analyses  |
| 5/25 | 12 PM | Begin work on analyses | Finalize analyses for final visualizations  |
| 5/27  | Before 11:59 PM | Sections assigned to complete on Checkpoint #2 notebook | Submit Project Checkpoint #2 EDA  |
| 6/1  | 12 PM  | Complete analyses; Draft results/conclusion/discussion| Discuss/edit final project |
| 6/3-6/10  | Times TBD | Finalize loose ends, work on project video | Finalize loose ends, work on project video |
| 6/10  | Before 11:59 PM  | NA | Turn in Final Project & Group Project Surveys |